In [1]:
import json
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
with open('../data/puzzles.json', 'r') as jsonfile:
    puzzle_data = json.load(jsonfile)

In [3]:
puzzles = []
solutions = []
for puzzle in puzzle_data:
    puzzles.append(puzzle["puzzle"])
    solutions.append(puzzle["solution"])
puzzles = np.array(puzzles)
solutions = np.array(solutions)

In [4]:
len(puzzles)

5300

In [10]:
puzzles_train, puzzles_test, solutions_train, solutions_test = train_test_split(puzzles, solutions, test_size=0.2, random_state=42)

In [11]:
len(puzzles_train)

4240

In [12]:
puzzles_train[0]

array([[5, 0, 0, 6, 7, 3, 1, 0, 2],
       [0, 0, 7, 0, 9, 4, 0, 3, 6],
       [0, 0, 4, 2, 5, 1, 8, 0, 9],
       [0, 9, 0, 4, 0, 8, 7, 0, 1],
       [2, 7, 6, 0, 0, 0, 9, 8, 4],
       [0, 0, 1, 0, 2, 7, 3, 0, 0],
       [0, 6, 2, 1, 8, 9, 0, 5, 0],
       [0, 0, 3, 0, 0, 6, 2, 1, 8],
       [4, 1, 0, 5, 3, 0, 0, 9, 7]])

In [ ]:
# MSE not appropriate --> will lead to 4 and 5 guesses
# Should be either correct or wrong
# Count the number of wrong ones as loss function
# WTF is sparse_categorical_crossentropy

In [13]:
puzzles_train = puzzles_train.reshape(-1, 81) / 9
puzzles_test = puzzles_test.reshape(-1, 81) / 9
solutions_train = solutions_train.reshape(-1, 81) / 9
solutions_test = solutions_test.reshape(-1, 81) / 9

In [18]:
def create_sudoku_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Dense(128, activation='relu', input_shape=(81,)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(81, activation='softmax')
    ])
    
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    
    return model

model = create_sudoku_model()

In [22]:
new_puzzle = np.array([
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
])

# Reshape the input to match the model's input shape
new_puzzle = new_puzzle.flatten()
new_puzzle = new_puzzle / 9.0  # Normalize the values between 0 and 1

# Perform the prediction
predictions = model.predict(np.array([new_puzzle]))

# Reshape the predictions back to the 9x9 grid shape
predictions = predictions.reshape((9, 9))

# Find the most probable values for each cell
solved_puzzle = np.argmax(predictions, axis=1)

# Reshape the solved puzzle back to the 9x9 grid shape
solved_puzzle = solved_puzzle.reshape((9, 9))

# Print the solved puzzle
print(solved_puzzle)

1/1 [==============================] - 0s 20ms/step


ValueError: cannot reshape array of size 9 into shape (9,9)

In [21]:
predictions

array([[0.01437321, 0.01560794, 0.01248061, 0.01009885, 0.01462195,
        0.01161344, 0.0138914 , 0.00972902, 0.01197504, 0.00755326,
        0.00969903, 0.01370753, 0.01155839, 0.01203171, 0.00870537,
        0.01026498, 0.01112598, 0.01366768, 0.01371307, 0.0101701 ,
        0.00903686, 0.01292316, 0.01086591, 0.01606416, 0.01072702,
        0.01021174, 0.01686424, 0.01259067, 0.01096443, 0.01021778,
        0.01727676, 0.01296812, 0.01361099, 0.01072106, 0.01223464,
        0.01124933, 0.01294846, 0.01115233, 0.00889868, 0.01216738,
        0.01219465, 0.01114055, 0.01569491, 0.01069487, 0.01151508,
        0.01095222, 0.00811825, 0.01361703, 0.01232372, 0.01152715,
        0.01208541, 0.01067103, 0.01774103, 0.01340362, 0.01457326,
        0.01028982, 0.01236868, 0.01076449, 0.00949747, 0.01465834,
        0.01613144, 0.01293257, 0.01011906, 0.01301018, 0.01873202,
        0.01287124, 0.01363545, 0.01536106, 0.01407051, 0.01340923,
        0.01485399, 0.00880601, 0.00782947, 0.01

In [14]:
puzzles_test[0]

array([0.55555556, 0.        , 0.        , 0.11111111, 0.        ,
       0.        , 0.88888889, 0.77777778, 0.44444444, 0.77777778,
       0.33333333, 0.        , 0.22222222, 0.66666667, 0.44444444,
       1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.77777778, 0.88888889, 0.        , 0.        ,
       0.33333333, 0.66666667, 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.66666667, 0.        , 0.44444444,
       0.33333333, 0.22222222, 0.66666667, 0.        , 0.        ,
       0.11111111, 1.        , 0.77777778, 0.55555556, 0.88888889,
       0.44444444, 0.11111111, 0.55555556, 0.33333333, 0.        ,
       0.        , 0.        , 0.22222222, 0.        , 0.        ,
       0.        , 0.22222222, 0.88888889, 0.55555556, 0.11111111,
       0.        , 0.66666667, 0.        , 0.66666667, 0.        ,
       0.        , 0.        , 0.33333333, 0.22222222, 0.44444444,
       0.        , 0.        , 0.        , 0.88888889, 0.11111

In [28]:
model.fit(puzzles_train, solutions_train, epochs=10, batch_size=32)

loss, accuracy = model.evaluate(puzzles_test, solutions_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

Epoch 1/10


InvalidArgumentError: Graph execution error:

Detected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\traitlets\config\application.py", line 1041, in launch_instance
      app.start()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\kernelapp.py", line 724, in start
      self.io_loop.start()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
      self._run_once()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
      handle._run()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\kernelbase.py", line 512, in dispatch_queue
      await self.process_one()
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\kernelbase.py", line 501, in process_one
      await dispatch(*args)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\kernelbase.py", line 408, in dispatch_shell
      await result
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\kernelbase.py", line 731, in execute_request
      reply_content = await reply_content
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\ipkernel.py", line 417, in do_execute
      res = shell.run_cell(
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\zmqshell.py", line 540, in run_cell
      return super().run_cell(*args, **kwargs)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 2945, in run_cell
      result = self._run_cell(
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3000, in _run_cell
      return runner(coro)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3203, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3382, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\IPython\core\interactiveshell.py", line 3442, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\woute\AppData\Local\Temp\ipykernel_20152\3776889529.py", line 1, in <module>
      model.fit(puzzles_train, solutions_train, epochs=10, batch_size=32)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1685, in fit
      tmp_logs = self.train_function(iterator)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1284, in train_function
      return step_function(self, iterator)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1268, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1249, in run_step
      outputs = model.train_step(data)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1051, in train_step
      loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\training.py", line 1109, in compute_loss
      return self.compiled_loss(
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\engine\compile_utils.py", line 265, in __call__
      loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 142, in __call__
      losses = call_fn(y_true, y_pred)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 268, in call
      return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\losses.py", line 2078, in sparse_categorical_crossentropy
      return backend.sparse_categorical_crossentropy(
    File "c:\Users\woute\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\backend.py", line 5660, in sparse_categorical_crossentropy
      res = tf.nn.sparse_softmax_cross_entropy_with_logits(
Node: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'
logits and labels must have the same first dimension, got logits shape [32,81] and labels shape [2592]
	 [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_4497]

In [ ]:
model.save('solve_model.h5')